### ISSUE TITLE
[feature request] Change VIP/Fav behavior and other ideas

### ISSUE THREAD

**Issue by LilacTimes** [vrcx-team/VRCX#230]
I just recently started using VRCX and from the get go, I don't quite understand how the vip list works?
It would be nice to be able to add players to said list arbitrarily, instead of basing it on what I presume are the vrc fav lists. 

On top of that, having a feature for infinite local fav lists would be nice. Grouping different friend groups together for easier organization. Maybe even go so far as to adding locally stored tags, like assigning a player as part of group A and group B etc.

One last thing- It would be nice if you could filter the big friends list by online status.

Just some random ideas or whatever. Thanks for your time <3

**Comment by Natsumi-sama** [comment]
Custom friend groups is something I have had planed for a while now but have yet to implement because it will take a long time to do.

I had sorting by status during testing but removed it because only online/cached users have their status visible.
I have since added an option to sort aside list to move all users in private instances to the bottom, this will be in next release.
