### ISSUE TITLE
[Feature Request] Auto Accept Requests or Invites

### ISSUE THREAD

**Issue by madamunkey** [vrcx-team/VRCX#495]
The ability to auto accept requests or invites from individual users, or perhaps, even utilizing the "Favorite Users" groups would be incredibly useful

Filters could be implemented too if context is desired, such as session type
this could be incredibly useful for anyone who uses No Hud, sleeps on orange, runs small personal events, or simply just don't want to bother

obviously making the feature easy to toggle off too as privacy matters

**Comment by LunarstarPony** [comment]
This would indeed be something nice to have x3

**Comment by Wasmachineman-NL** [comment]
Autoaccepting your own invites would save me a few seconds if I want to switch lobbies, which I often do if there's no interesting Pug goers to talk to.

**Comment by Myrkie** [comment]
> Autoaccepting your own invites would save me a few seconds if I want to switch lobbies, which I often do if there's no interesting Pug goers to talk to.

not possible VRCX cannot interact with the game client on your behalf vrcx can only access vrchat data through the output log and API.

**Comment by Wasmachineman-NL** [comment]
Wouldn't that make OP's feature request impossible then?

**Comment by Myrkie** [comment]
> Wouldn't that make OP's feature request impossible then?

no that is possible since its a request TO you that's sent through the API and then the request is sent back to the requester with a response. VRCX just has to respond to the request which is sent back to the requester of the invite, in the game client accepting an invite activates vrchat's flow manager and tells you to go to the instance.

when you get an invite in the feed its just letting you know, joining an instance requires either vrchat starting with a launch option or you accept the invite yourself.
![image](https://github.com/vrcx-team/VRCX/assets/20288698/42b46798-384b-4cd6-9ef6-2b944d67ad72)


but when you get a request invite you can either accept the request respond to it or delete it which sends out a response to that user, if you're a instance creator or moderator you can send out an accept

![image](https://github.com/vrcx-team/VRCX/assets/20288698/4663fa93-5d30-4d58-be32-2898d415d2ca)

**Comment by Wasmachineman-NL** [comment]
> > Wouldn't that make OP's feature request impossible then?
> 
> no that is possible since its a request TO you that's sent through the API and then the request is sent back to the requester with a response. VRCX just has to respond to the request which is sent back to the requester of the invite, in the game client accepting an invite activates vrchat's flow manager and tells you to go to the instance.
> 
> when you get an invite in the feed its just letting you know, joining an instance requires either vrchat starting with a launch option or you accept the invite yourself. ![image](https://user-images.githubusercontent.com/20288698/245814715-42b46798-384b-4cd6-9ef6-2b944d67ad72.png)
> 
> but when you get a request invite you can either accept the request respond to it or delete it which sends out a response to that user, if you're a instance creator or moderator you can send out an accept
> 
> ![image](https://user-images.githubusercontent.com/20288698/245815011-4663fa93-5d30-4d58-be32-2898d415d2ca.png)

interesting.ogg

**Comment by Natsumi-sama** [comment]
There is already another program that can do this https://github.com/Raphiiko/OyasumiVR

**Comment by Myrkie** [comment]
To clarify, VRCX can access anything through vrchat's API and websocket that is accessible to a normal user, joining an instance is done through the games encrypted network called Photon which we don't nor will ever have access too, the only way for vrcx to put you into an instance currently is to close vrchat and then start it up again with a launch, the link natsumi just provided is for the original posters request of "Automatically accept invite requests on VRChat"
