### ISSUE TITLE
Clicking user only searches their name?

### ISSUE THREAD

**Issue by JanieUwU** [vrcx-team/VRCX#519]
Sometimes for random users when clicking on their name in the player joined/left logs it switches tabs to the search and searches them. Am I missing a reason on why this happens?

**Comment by Natsumi-sama** [comment]
Because VRChat doesn't log userId's to gameLog when clicking on a user it has to search their displayName to get their userId and because VRChats user search is hot garbage it fails a lot of the time sending you to the user search page so you can try find them manually. You can feed VRCX most userIds of players in your instance by adding this VRChat launch parameter `--log-debug-levels=API`.

**Comment by JanieUwU** [comment]
I see, that sucks but thank you for the work around!
