### ISSUE TITLE
[Feature Request] Better Screenshot manager

### ISSUE THREAD

**Issue by spyro12675** [vrcx-team/VRCX#529]
When we had mods for VRC there was a mod called [Screenshot Manager](https://github.com/DragonPlayerX/ScreenshotManager) and you could upload pics from in vrc but now we can't do that so i was wondering if we could get that in VRCX

**Comment by Myrkie** [comment]
at most vrcx could add WebHook support, vrcx does already support the option of including metadata world name and present players inside the files if you enable it in vrcx settings > Screenshot helper
![image](https://user-images.githubusercontent.com/20288698/235517463-9aad4748-9f8f-42a5-abc7-8150cc60f2f0.png)

**Comment by Natsumi-sama** [comment]
If you open the image in `Settings > Advanced > Screenshot Metadata` you can upload images from there.

**Comment by Protected** [comment]
As the original author of the metadata feature (for LFS) thank you all for keeping this stuff alive. I have a huge archive of tagged photos ;)

I added support of the VRCX format to [my Discord bot](https://github.com/Protected/rowboat/blob/master/behavior/VRChatPhotos.js#L1003) a couple weeks ago, if anyone's interested. It's not the easiest thing to set up. The way it functions is the bot checks the uploaded picture and if metadata is detected deletes the message, generates a temporary webhook with the same name as the uploader and re-shares the picture in an embed alongside the metadata. Because Discord strips EXIF out of jpeg uploads, it requires PNG photos/screenshots.

I also had a WIP [web-based client-side tool](https://keepgoing.discworld.eu/templfmr/) made in React that placed clickable labels above the players in each photo. No longer possible now that there's no way to get the players' viewpoint coordinates, so it's not worth updating for the new format (I wish it was!)
