### ISSUE TITLE
[Feature Request] add pronouns feature

### ISSUE THREAD

**Issue by aabbey-stack** [vrcx-team/VRCX#585]
**Explain in detail what your suggested feature would be used for.**
This feature would make you able to specify pronouns on your VRCX profile page. For example I like the design of GitHub's pronouns little bit more than discord's. 
![firefox_BZnURaWuK6](https://github.com/vrcx-team/VRCX/assets/61197745/52e54dc2-b455-4611-8c07-98c9ac33a63d)
![firefox_quZepUKBFG](https://github.com/vrcx-team/VRCX/assets/61197745/200073a6-9520-4100-a7a5-dd2cfbbb88b6)

**Describe how it would look if it requires a UI.**
Could be on the place where notes used to be in the old VRCX or next to the display name where trust ranks are. The drop-down box with most common options plus custom field would be the ideal choice as well in my opinion. It might require adding some additional bad word filtering thought . 

**Explain why people would want to use it.**
It recently came to my attention how much people enjoy pronouns feature. Even GitHub has added it and discord is rolling it out too. As it stands this feature is really popular with users, but of course let me know what you think.

**Comment by TayouVR** [comment]
how would this be stored and sent to other users then? should it be like the first line of the bio?
VRCX can't just add arbitrary data to your VRChat account.

**Comment by TayouVR** [comment]
I suppose PronounDB would work, true

**Comment by Natsumi-sama** [comment]
Nah same problem still stands with PronounDB

**Comment by aabbey-stack** [comment]
Also I find the username field kinda useless I've figured out where the location for such feature could be. This would also show for other users by making an API call to pronoun db or any other provider (self hosing could be an option too since VRCX could protect itself by only allowing logged in accounts to make post requests). 
![VRCX_bLDWIl4b9E](https://github.com/vrcx-team/VRCX/assets/61197745/1d39940e-a041-42d2-ad08-ae8e1ea42fd3)

**Comment by Natsumi-sama** [comment]
How does PronounDB associate with Discord ids? you would need a way to verify the user is who they say they are.

**Comment by Natsumi-sama** [comment]
That's out of scope and a lot more work than it's worth, my to do list is already massive and I don't plan on adding to it.

**Comment by BLANKE1** [comment]
A better implementation of this is just to check for pronouns in the bio/status and then you could put that info somewhere in the main profile section just like how [tetra-fox's ProPlates did it](https://github.com/tetra-fox/VRCMods). This way this feature is more used instead of just being selective to just VRCX users, another way is just get VRChat to actually implement a dedicated field or whatever.

**Comment by WOLFIE-OG** [comment]
I personally don't really see the need for pronouns but it could be added to the local VRCX DB or a use discords oauth2 feature to allow users to link their vrcx to discord and grab the information from their.

**Comment by Myrkie** [comment]
out of the scope for vrcx

**Comment by DJDavid98** [comment]
I'm currently seeing an option to set pronouns in the app and I am left wondering what is the data source for this, since I can see it for my friends for whom I definitely did not set it myself nor is it coming from their bio. Is this stored by VRChat and set by the users, or somehow handled within VRCX entirely? I couldn't find anything on the VRChat Discord server or the releases in this repo regarding this feature.

**Comment by Nekromateion** [comment]
VRChat has added pronouns as part of their API, it is currently not in any release of the game and merely implemented into VRCX because it exists in the API.
