### ISSUE TITLE
[Bug] Windows Defender detects a Trojan in Nightly VRCX

### ISSUE THREAD

**Issue by Chirping-Cat** [vrcx-team/VRCX#752]
**Describe the bug**
After updating to the latest nightly, Windows Defender detects VRCX as a Trojan and quarantines it.

**To Reproduce**
1. Upgrade to latest nightly at the time of submission of this ticket.
2. Windows defender will block and quarantine VRCX, stating it is a Trojan.

**Expected behavior**
Windows Defender should not be detecting VRCX as a Trojan

**Screenshots**
![Screenshot 2024-03-21 121216](https://github.com/vrcx-team/VRCX/assets/113987746/ab60acec-de57-40ee-8233-1f8554fe915b)

**What version you are running**
Latest Nightly at Time of Submission

**Comment by Myrkie** [comment]
Wacatac.B1ml is a well known AI detection that can be ignored

**Comment by Myrkie** [comment]
go through with the process of update your windows defender security intelligence database and these errors should go away https://github.com/vrcx-team/VRCX/issues/568#issuecomment-1593373667

**Comment by Chirping-Cat** [comment]
Instructions worked fine.

https://www.virustotal.com/gui/file/58f57899fb44cce3fe51985c96fe36e279320489690d83d14e81eabaaf1139be/detection

Bitdefender flags it using the same algorithm so you may get more of these tickets. Any idea why this particular build seems to be problematic?

**Comment by Myrkie** [comment]
> Instructions worked fine.
> 
> https://www.virustotal.com/gui/file/58f57899fb44cce3fe51985c96fe36e279320489690d83d14e81eabaaf1139be/detection
> 
> Bitdefender flags it using the same algorithm so you may get more of these tickets. Any idea why this particular build seems to be problematic?

its been a common issue, its because of the way the [VRCX updater](https://github.com/vrcx-team/VRCX/blob/master/Dotnet/Update.cs#L42) works and has been an ongoing issue, usually we get away with stable being fine as stable is built weeks in advanced before release and submitted to Microsoft for manual review before being published so people have a chance to receive the updated definitions before a false flag can occur. this would be fixed with a Signing certificate but currently the requirements for a EV signing cert is rather insane and overly expensive.

**Comment by DubyaDude** [comment]
Rescanning it dropped a handful, the executable likely got enough reputation now.
