### ISSUE TITLE
[Feature Request] Allow customization of the invite message

### ISSUE THREAD

**Issue by EntityReborn** [vrcx-team/VRCX#760]
**Explain in detail what your suggested feature would be used for.**
Update configurations to allow customization (or removal) of the message used in invite messages, replacing the current "this is a generated invite to X" message.

**Describe how it would look if it requires a UI.**
When clicking the invite button in all views that show this button, pop up a text box prompt asking for the message to be used, as well as offering an option to not use an invite message at all.
This box would be populated either by a default value provided in the settings section, or would show the previously used value.
This would have Cancel and OK/Invite buttons.

This could potentially also have a "last 5 messages" list that could be selected from as well for extra bonus points.

**Explain why people would want to use it.**
Customization of text being sent in an invite, to customize the experience for the receiving user. 
By allowing customization, this also provides the ability of removing an indicator that a user is using VRCX, if so desired.

**Comment by Natsumi-sama** [comment]
This message is generated by VRChat not VRCX and is the same as the websites, the invite button is meant to be a easy one click self invite, if you'd like to invite with a message you can click on the instance number and it will bring up the option to invite with message. Last time I checked self inviting using the invite with message endpoint would fail for some instance types, this is why the button is greyed out because the user wont have permission to invite someone to this instance type (not even their self).

**Comment by EntityReborn** [comment]
I have actually not used the website to create invites, good to know!
