### ISSUE TITLE
[Bug] self invide while on red

### ISSUE THREAD

**Issue by Hackebein** [vrcx-team/VRCX#775]
**Describe the bug**
Inviting myself while on red doesn't work. Instead it shows "You can't invite yourself in 'Do Not Disturb' mode"

**To Reproduce**
1. Set status to red/DND
2. Try to invide yourself
3. See error

**Expected behavior**
I expect to recieve an invite as i would do when inviting myself from the website

**What version you are running**
VRCX Nightly 2024-04-13T11.24-0dfdc9f

**Comment by Nekromateion** [comment]
This is in fact how the application is meant to behave.
While the VRChat website allows you to invite yourself there is no point in doing so since the game client will not show you the invite while you are on Do Not Disturb, the message is there to prevent confusion.
Please bring this up with VRChat if you feel that this is something you need.

**Comment by Hackebein** [comment]
I'm aware of this behaviour. Even when if the game client doesn't show the notifications the notification still gets send out and can 
 be read by other programs which are listening on websocket. Therefore I still see VRCX having a bug here. I would recommend to adjust to VRChats behaviour and to send out the request. A Notification that this might not work is still a possability to show.

No need to bring this to VRChat, since the bug is here and not at VRChat.

**Comment by Natsumi-sama** [comment]
This is working as intended it's a feature not a bug, users may not realize that they're on DnD or know about how it will prevent them from receiving their invite in-game, additionally I cannot think of a single use case where this would be useful regardless.
